video_prompts = [
    "A cosmic jellyfish floating through space, bioluminescent tentacles dancing in zero gravity, ethereal, otherworldly, photorealistic",
    "Time-lapse of a cherry blossom tree through seasons, petals falling in gentle wind, soft natural lighting, Studio Ghibli style",
    "Steampunk city transformation, brass gears turning, steam rising, Victorian architecture evolving, golden hour lighting",
    "Northern lights dancing across a frozen lake, reflections rippling, stars twinkling, ultra HD quality",
    "Watercolor paint spreading across white paper, colors bleeding and mixing, macro shot, artistic",
    "Crystal growing time-lapse, geometric patterns forming, iridescent reflections, mineralogical accuracy",
    "Deep sea bioluminescent creatures, dark blue waters, particles floating, National Geographic style",
    "Abstract fluid art, metallic colors swirling, marble patterns forming, high contrast",
    "Ancient temple emerging from jungle, vines receding, sunbeams filtering through leaves, archaeological realism",
    "Cyberpunk street scene, neon signs flickering, hovercars passing, rain-slicked streets",
    "Desert sand dunes shifting in wind, golden light, minimalist landscape, cinematic wide shot",
    "Butterfly emerging from chrysalis, detailed metamorphosis, macro photography, natural lighting",
    "Urban landscape transforming through decades, architectural evolution, historical accuracy",
    "Fractal patterns growing and evolving, kaleidoscopic colors, mathematical precision",
    "Storm clouds forming over ocean, lightning strikes, dramatic lighting, weather photography",
    "Paper origami folding itself, traditional patterns, clean white paper, studio lighting",
    "Autumn leaves falling in forest, warm colors, sunlight filtering through trees, photorealistic",
    "Ice crystals forming on window, intricate frost patterns, macro detail, winter morning light",
    "Vintage vinyl record spinning, psychedelic patterns emerging, retro color palette",
    "Bamboo forest growing, morning mist, zen atmosphere, traditional Chinese painting style",
    "Solar system planets orbiting, cosmic dust, stellar backgrounds, astronomical accuracy",
    "Urban garden growing on rooftop, time-lapse, sustainable architecture, documentary style",
    "Ancient scroll unrolling, Chinese calligraphy appearing, ink wash effects, traditional art",
    "Volcanic landscape forming, lava flows, ash clouds, geological accuracy",
    "Hummingbird hovering at flower, slow motion, iridescent feathers, nature photography",
    "Art deco building constructing itself, gold and black details, architectural precision",
    "Coral reef coming to life, tropical fish appearing, underwater photography",
    "DNA double helix spinning, molecular animation, scientific visualization",
    "Traditional Japanese tea ceremony, steam rising, wabi-sabi aesthetics, contemplative",
    "Wild horses running through mountain valley, dust clouds, golden hour, cinematic",
    "Medieval castle construction time-lapse, stone by stone, historical accuracy",
    "Quantum particles interacting, abstract visualization, scientific accuracy",
    "Rain falling on tropical leaves, water droplets, macro photography, natural lighting",
    "Gothic cathedral interior, light rays through stained glass, architectural detail",
    "Space station assembly in orbit, technical accuracy, Earth backdrop",
    "Traditional pottery being thrown, clay forming, artisan craftsmanship",
    "Wind turbines in misty landscape, renewable energy, minimalist composition",
    "Ancient Egyptian hieroglyphs appearing on stone, archaeological detail",
    "Modern dance performance, abstract movements, minimalist stage",
    "Arctic glacier calving, ice chunks falling, environmental documentary",
    "Traditional African tribal dance, authentic costumes, cultural respect",
    "Clockwork mechanism assembling itself, brass gears, technical precision",
    "Rainbow forming over waterfall, water spray, natural phenomenon",
    "Traditional Indian mandala forming, intricate patterns, spiritual art",
    "Forest fire regeneration, new growth emerging, environmental cycle",
    "Zen garden being raked, sand patterns, meditative atmosphere",
    "Classic car restoration time-lapse, mechanical detail, vintage aesthetic",
    "Byzantine mosaic assembling itself, religious iconography, historical accuracy",
    "Fungal network growing underground, scientific accuracy, macro view",
    "Traditional Celtic knot weaving itself, intricate patterns, cultural authenticity"
]